### ISSUE TITLE
Cisco ISE VM is not loading

### ISSUE THREAD

**Issue by automagicallyio** [grg1bbs/Terraform_ISE_Azure_Deployment#2]
Hello,

I am experiencing issue similar to #1. I am using this repository code as example. Here is what I am seeing:

- VM starts and I can ping it
- I cannot connect to the VM via SSH. It does not matter if I create VM with SSH key authentication enabled OR SSH password authentication enabled. Very weird. 
- I have also for the fun of it created Ubuntu VM using the same code except for source_image_reference part (which uses Ubuntu 0001-com-ubuntu-server-focal 20_04-lts latest image) and everything comes up green. I can connect to it using the same SSH key and/or password.
- Web portal also does not come up
- in Serial console, everything appears to look normal.
- I have created a snapshot for the VM disk, then created new disk from it and attached it to another VM, so that I can access the disk contents. Under root partition, in CSCOcpm/logs folder, I have found ise-psc.logs (which appears to be provisioning log file), I can see a lot of errors. Not sure if they are related to this issue though, but I can share the file if necessary.

I can create VM using Azure Portal and everything comes up as expected, but not when I use Terraform. It's very frustrating. Please help.

Thank you,
Max

**Comment by grg1bbs** [comment]
@automagicallyio,

I was never able to replicate the problems from Issue #1 and there was no update from the poster, so I'm not sure what was needed to resolve that. I tested the same code yesterday in my Azure tenant using the following versions and it worked as expected. After waiting 30-40 minutes for the build to complete, I could see that the application server was started and was able to connect to the GUI.

Terraform v1.6.6
on darwin_amd64
\+ provider registry.terraform.io/hashicorp/azurerm v3.85.0

The most common issue I see is the use of a password that does not meet the requirements. I use the password of "Ch@ngePassw0rd" in my code and it works consistently. I would suggest you try using the same as ISE requires changing the GUI password upon first login.

_"I cannot connect to the VM via SSH. It does not matter if I create VM with SSH key authentication enabled OR SSH password authentication enabled. Very weird."_

ISE cloud deployments only support SSH key authentication, so that must be used.
 - are you getting a specific error?
 - how are you generating the SSH key for the VM?

_"in Serial console, everything appears to look normal."_

What does "normal" mean?
 - are you getting a linux shell or the ISE shell?
 - If you're getting the ISE shell, what do you see from the output of "show application status ise" ?

ISE is a virtual appliance, not an application running on top of a basic Linux OS. It cannot be treated like a generic Linux installation and deviations from the documented installation procedures will cause issues.

If you would like to post the relevant TF code blocks you are using, I'm happy to have a look at it.

After the VM build completes, are you seeing the correct decoded user_data in the **Settings > Configuration** blade for the VM?
Example from my lab:

<img width="744" alt="Screenshot 2023-12-19 at 12 53 08 pm" src="https://github.com/grg1bbs/Terraform_ISE_Azure_Deployment/assets/103554967/e2102744-331f-420b-909e-8cd6004fbf9f">

**Comment by automagicallyio** [comment]
Thank you for a quick response.

Here is an error I get when trying to connect via SSH:

_Permission denied (publickey)_

SSH key is generated using: _ssh-keygen -m PEM -t rsa -b 4096_  How do you generate a key? I am running on a Windows machine btw.

_"in Serial console, everything appears to look normal."_ I meant to say when I look under boot diagnostics logs in azure portal, nothing looks out of ordinary.

**Comment by grg1bbs** [comment]
I generated my ssh key awhile back, so I think I created it directly in Azure and saved the private/public key files locally.

However, I just tested creating the keypair using the same ssh-keygen option and spun up another ISE instance using that key. After waiting 30min for the build to complete, I was able to connect via SSH from both my MacOS and Windows CLI.

Example:
```
> ssh -i test_azure_sshkey.pem iseadmin@x.x.x.x
Last login: Wed Dec 20 23:03:47 2023 from y.y.y.y
Failed to log in 0 time(s)

iseadmin connected from y.y.y.y using ssh on ise32-az1
ise32-az1/iseadmin#
```

**Comment by automagicallyio** [comment]
Here is my User Data
![image](https://github.com/grg1bbs/Terraform_ISE_Azure_Deployment/assets/30164734/0f1e46c3-7607-470b-bff8-56833a77c1ce)

**Comment by grg1bbs** [comment]
The user data appears to be encoded/decoded correctly, so that does not appear to be an issue. Are you able to share the 'azurerm_linux_virtual_machine' resource block you're using?

**Comment by automagicallyio** [comment]
Issue got resolved. The failures were caused  caused by the line endings in the user data file. My VS Code was set to automatically detect and set line endings and since I was running on Windows, it chose CRLF instead of LF. As soon as I changed line endings to Unix style, Cisco ISE came up.

Thank you.

**Comment by grg1bbs** [comment]
Thanks @automagicallyio for sharing the source of the issue and how you resolved it.
